# Generated by Django 3.2.8 on 2021-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('answer', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('1', 'General'), ('2', 'Personal'), ('3', 'Technical'), ('4', 'Behavioural')], default=1, max_length=1)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default=1, max_length=1)),
            ],
        ),
    ]
