# Generated by Django 3.2.8 on 2021-10-20 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('number_of_questions', models.IntegerField(null=True)),
                ('category', models.CharField(blank=True, choices=[('1', 'General'), ('2', 'Personal'), ('3', 'Technical'), ('4', 'Behavioural')], default='G', max_length=1, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
